- hosts: RUNNERVM
  tasks:
  - name: Change hostname to centos-68-build
    hostname:
      name: "centos-68-build"
    become: true

  - name: Modify /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1[ \t]+localhost'
      line: '127.0.0.1 localhost centos-68-build'
      state: present
    become: true
